exclude: "(migrations)"

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-json
    -   id: check-toml
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.282
    hooks:
    -   id: ruff

-   repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
    -   id: black

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.4.1
    hooks:
    -   id: mypy
        args: [--strict, --ignore-missing-imports]
        additional_dependencies:
            - psycopg[binary]
            - python-decouple
            - django-stubs
            - djangorestframework-stubs
            - djangorestframework
            - django-cors-headers
            - django-filter
            - drf_spectacular
            - pytest
            - pytest-django
            - celery
            - django_celery_results
            - django_celery_beat
            - django_countries
