version: "3.8"

services:
  deputy-app:
    container_name: deputy_app
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/deputy
    env_file:
      - .env
    depends_on:
      - deputy-db
      - deputy-mq
    restart: unless-stopped
    networks:
      - deputy-net
    stdin_open: true  # docker run -i
    tty: true         # docker run -t

  deputy-db:
    container_name: deputy_db
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    volumes:
      - deputy-db-data:/var/lib/postgresql/data
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - deputy-net

  deputy-mq:
    container_name: deputy_mq
    image: rabbitmq:3-management-alpine
    hostname: deputy_mq
    env_file:
      - .env
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped
    networks:
      - deputy-net

  deputy-worker:
    container_name: deputy_worker
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/deputy
    env_file:
      - .env
    depends_on:
      - deputy-db
      - deputy-mq
    restart: unless-stopped
    networks:
      - deputy-net
    command: poetry run celery -A config worker -l INFO

  deputy-beat:
    container_name: deputy_beat
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/deputy
    env_file:
      - .env
    depends_on:
      - deputy-db
      - deputy-mq
    restart: unless-stopped
    networks:
      - deputy-net
    command: poetry run celery -A config beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler

  deputy-flower:
    container_name: deputy_flower
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "5555:5555"
    volumes:
      - .:/deputy
    env_file:
      - .env
    depends_on:
      - deputy-db
      - deputy-mq
    restart: unless-stopped
    networks:
      - deputy-net
    command: poetry run celery -A config flower -l INFO

volumes:
  deputy-db-data:

networks:
  deputy-net:
