version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "5555:5555"
      - "8000:8000"
    volumes:
      - .:/deputy
    env_file:
      - .env
    depends_on:
      - db
      - mq
    restart: unless-stopped
    networks:
      - deputy-net
    stdin_open: true  # docker run -i
    tty: true         # docker run -t

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    volumes:
      - deputy-db-data:/var/lib/postgresql/data
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - deputy-net

  mq:
    image: rabbitmq:3-management-alpine
    env_file:
      - .env
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped
    networks:
      - deputy-net

  worker:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/deputy
    env_file:
      - .env
    depends_on:
      - db
      - mq
    restart: unless-stopped
    networks:
      - deputy-net
    command: celery -A config worker -l INFO

volumes:
  deputy-db-data:

networks:
  deputy-net:
