version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: docker/prod/Dockerfile
    ports:
      - "5555:5555"
      - "8000:8000"
    env_file:
      - .env
    environment:
      - ALLOWED_HOSTS=deputy.zube.dev
      - CSRF_TRUSTED_ORIGINS=https://deputy.zube.dev
    depends_on:
      - db
      - mq
      - caddy
    networks:
      - deputy-net
    labels:
      caddy: deputy.zube.dev
      caddy.reverse_proxy: "{{upstreams 8000}}"
    restart: unless-stopped
    stdin_open: true  # docker run -i
    tty: true         # docker run -t

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    volumes:
      - deputy-db-data:/var/lib/postgresql/data
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - deputy-net

  mq:
    image: rabbitmq:3-management-alpine
    env_file:
      - .env
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped
    networks:
      - deputy-net

  worker:
    build:
      context: .
      dockerfile: docker/prod/Dockerfile
    env_file:
      - .env
    environment:
      - ALLOWED_HOSTS=deputy.zube.dev
      - CSRF_TRUSTED_ORIGINS=https://deputy.zube.dev
    depends_on:
      - db
      - mq
    restart: unless-stopped
    networks:
      - deputy-net
    command: celery -A config worker -l INFO

  caddy:
    image: lucaslorentz/caddy-docker-proxy:2.8-alpine
    ports:
      - "80:80"
      - "443:443"
    environment:
      - CADDY_INGRESS_NETWORK=deputy-net
    networks:
      - deputy-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - deputy-caddy-data:/data
    restart: unless-stopped

volumes:
  deputy-db-data:
  deputy-caddy-data: {}

networks:
  deputy-net:
