#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

echo "Running migrations..."
python manage.py migrate --noinput

echo "Creating superuser..."
python manage.py createsuperuser --noinput 2> /dev/null || true

echo "Running collectstatic..."
python manage.py collectstatic --noinput

echo "Running server..."
exec python manage.py runserver 0.0.0.0:8000
