#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

# initialize the background tasks scheduler
echo "Initializing tasks..."
python manage.py init_tasks

# run supervisord to manage the background tasks
echo "Running supervisord..."
supervisord -c /etc/supervisor/supervisord.conf
