# Generated by Django 4.2.5 on 2023-09-05 04:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proxy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="proxy",
            name="check_fail_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="number of times the proxy has been checked since it worked last.",
                verbose_name="check fail count",
            ),
        ),
    ]
