#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

docker run --rm --detach --name beat \
    --env-file .env \
    --network deputy-net \
    ziibii88/deputy:latest \
    celery --app config beat --scheduler django_celery_beat.schedulers:DatabaseScheduler --loglevel INFO
