WEBSITES = [
    "https://google.com/",
    "https://youtube.com/",
    "https://facebook.com/",
    "https://instagram.com/",
    "https://baidu.com/",
    "https://wikipedia.org/",
    "https://qq.com/",
    "https://taobao.com/",
    "https://tmall.com/",
    "https://yahoo.com/",
    "https://amazon.com/",
    "https://twitter.com/",
    "https://sohu.com/",
    "https://reddit.com/",
    "https://live.com/",
    "https://vk.com/",
    "https://twitch.tv/",
    "https://jd.com/",
    "https://sina.com.cn/",
    "https://weibo.com/",
    "https://yandex.ru/",
    "https://360.cn/",
    "https://blogspot.com/",
    "https://netflix.com/",
    "https://linkedin.com/",
    "https://wordpress.com/",
    "https://microsoft.com/",
    "https://office.com/",
    "https://tumblr.com/",
    "https://googleusercontent.com/",
    "https://github.com/",
    "https://imdb.com/",
    "https://stackoverflow.com/",
    "https://imgur.com/",
    "https://aliexpress.com/",
    "https://fc2.com/",
    "https://bing.com/",
    "https://aliexpress.com/",
    "https://naver.com/",
    "https://ok.ru/",
    "https://apple.com/",
    "https://github.io/",
    "https://chinadaily.com.cn/",
    "https://google.com.hk/",
    "https://whatsapp.com/",
    "https://tianya.cn/",
    "https://pornhub.com/",
    "https://xvideos.com/",
    "https://xhamster.com/",
    "https://xnxx.com/",
    "https://healthline.com/",
    "https://tripadvisor.com/",
    "https://webmd.com/",
    "https://homedepot.com/",
    "https://indeed.com/",
    "https://target.com/",
    "https://nytimes.com/",
    "https://espn.com/",
    "https://foxnews.com/",
    "https://mapquest.com/",
    "https://allrecipes.com/",
    "https://quora.com/",
    "https://gamepedia.com/",
    "https://quizlet.com/",
    "https://bestbuy.com/",
    "https://rottentomatoes.com/",
    "https://cnet.com/",
    "https://zillow.com/",
    "https://udemy.com/",
    "https://coursera.com/",
    "https://fedex.com/",
    "https://usps.com/",
    "https://speedtest.net/",
    "https://chase.com/",
    "https://hulu.com/",
    "https://businessinsider.com/",
    "https://dictionary.com/",
    "https://weather.com/",
    "https://verizon.com/",
    "https://forbes.com/",
    "https://expedia.com/",
    "https://foodnetwork.com/",
    "https://macys.com/",
    "https://ign.com/",
    "https://capitalone.com/",
    "https://costco.com/",
    "https://glassdoor.com/",
    "https://yellowpages.com/",
    "https://bbc.com/",
    "https://adobe.com/",
    "https://jetbrains.com/",
    "https://fandom.com/",
    "https://booking.com/",
    "https://etsy.com/",
    "https://lowes.com/",
    "https://steampowered.com/",
    "https://britannica.com/",
    "https://roblox.com/",
    "https://genius.com/",
    "https://washingtonpost.com/",
]

USER_AGENTS = [
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
    "AppleWebKit/537.36 (KHTML, like Gecko) "
    "Chrome/91.0.4472.124 Safari/537.36",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
    "AppleWebKit/537.36 (KHTML, like Gecko) "
    "Chrome/92.0.4515.107 Safari/537.36",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
    "AppleWebKit/537.36 (KHTML, like Gecko) "
    "Chrome/91.0.4472.114 Safari/537.36",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
    "AppleWebKit/537.36 (KHTML, like Gecko) "
    "Chrome/91.0.4472.164 Safari/537.36",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
    "AppleWebKit/537.36 (KHTML, like Gecko) "
    "Chrome/92.0.4515.107 Safari/537.36",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
    "AppleWebKit/537.36 (KHTML, like Gecko) "
    "Chrome/91.0.4472.164 Safari/537.36",
    "Mozilla/5.0 (X11; Linux x86_64) " "AppleWebKit/537.36 (KHTML, like Gecko) " "Chrome/91.0.4472.114 Safari/537.36",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
    "AppleWebKit/537.36 (KHTML, like Gecko) "
    "Chrome/91.0.4472.114 Safari/537.36",
    "Mozilla/5.0 (X11; Linux x86_64) " "AppleWebKit/537.36 (KHTML, like Gecko) " "Chrome/92.0.4515.107 Safari/537.36",
    "Mozilla/5.0 (Windows NT 6.1; Win64; x64) "
    "AppleWebKit/537.36 (KHTML, like Gecko) "
    "Chrome/91.0.4472.124 Safari/537.36",
]
