name: CD

on:
  push:
    branches: ["master", "main"]

concurrency:
  group: cd-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PYTHON_VERSION: 3.11
  POETRY_VERSION: 1.5.1

jobs:
  tests:
    uses: ./.github/workflows/ci.yml

  build:
    name: "Deputy Build"
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/prod/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/deputy:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/deputy:${{ github.sha }}

  deploy:
    name: "Deputy Deploy"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: appleboy/ssh-action@v1.0.0  # deploy using ssh
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            docker stop deputy || true
            docker rm deputy || true
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/deputy:latest
            ./run_deputy
